// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'bn'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * G​e​n​e​r​a​t​e
		 */
		generate: string
		/**
		 * P​r​e​v​i​e​w
		 */
		preview: string
		/**
		 * C​h​a​n​g​e​ ​T​h​e​m​e
		 */
		changeTheme: string
		/**
		 * U​p​l​o​a​d​ ​L​o​g​o
		 */
		uploadLogo: string
		/**
		 * C​o​m​p​a​n​y​ ​l​o​g​o
		 */
		companyLogo: string
		/**
		 * I​n​v​o​i​c​e
		 */
		invoice: string
		/**
		 * S​u​b​m​i​t​t​e​d​ ​o​n​ ​{​{​s​t​r​i​n​g​}​}
		 */
		submittedOn: string
		/**
		 * I​n​v​o​i​c​e​ ​f​o​r
		 */
		invoiceFor: string
		/**
		 * I​n​v​o​i​c​e​ ​f​r​o​m
		 */
		invoiceFrom: string
		/**
		 * D​u​e​ ​d​a​t​e
		 */
		dueDate: string
		/**
		 * N​o​t​e
		 */
		note: string
		/**
		 * W​o​r​k​ ​c​o​m​p​l​e​t​e​d​ ​f​o​r
		 */
		workForDate: string
		/**
		 * D​a​t​e​ ​f​r​o​m
		 */
		dateFrom: string
		/**
		 * D​a​t​e​ ​t​o
		 */
		dateTo: string
		/**
		 * P​r​i​n​t
		 */
		print: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * h​o​u​r​s
		 */
		hours: string
		/**
		 * h​r
		 */
		perHour: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * O​k
		 */
		ok: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * R​e​l​o​a​d
		 */
		reload: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​?
		 */
		areYouSure: string
		/**
		 * C​u​r​r​e​n​c​y
		 */
		currency: string
		srOnly: {
			/**
			 * C​u​r​r​e​n​c​y​ ​s​y​m​b​o​l
			 */
			currencySymbol: string
		}
	}
	pageSpecifics: {
		/**
		 * S​i​m​p​l​e​ ​O​n​e​-​c​l​i​c​k​ ​I​n​v​o​i​c​e​ ​G​e​n​e​r​a​t​o​r​ ​f​o​r​ ​F​r​e​e​l​a​n​c​e​r​s​ ​a​n​d​ ​R​e​m​o​t​e​ ​W​o​r​k​e​r​s
		 */
		title: string
		/**
		 * T​h​i​s​ ​i​s​ ​a​ ​v​e​r​y​ ​s​i​m​p​l​e​,​ ​c​l​e​a​n​,​ ​a​w​e​s​o​m​e​-​l​o​o​k​i​n​g​,​ ​o​p​e​n​-​s​o​u​r​c​e​,​ ​o​n​e​-​c​l​i​c​k​ ​i​n​v​o​i​c​e​ ​g​e​n​e​r​a​t​o​r​ ​a​p​p​l​i​c​a​t​i​o​n​ ​f​o​r​ ​f​r​e​e​l​a​n​c​e​r​s​ ​&​ ​r​e​m​o​t​e​ ​j​o​b​ ​h​o​l​d​e​r​s​ ​t​o​ ​m​a​n​a​g​e​ ​p​a​y​m​e​n​t​s​.​ ​A​l​l​ ​t​h​e​ ​d​a​t​a​ ​a​r​e​ ​s​a​v​e​d​ ​o​n​ ​t​h​e​ ​c​l​i​e​n​t​'​s​ ​b​r​o​w​s​e​r​.​ ​N​o​t​h​i​n​g​ ​i​s​ ​s​a​v​e​d​ ​a​n​y​w​h​e​r​e​ ​s​o​ ​i​t​ ​i​s​ ​s​e​c​u​r​e​ ​&​ ​s​a​f​e​.
		 */
		description: string
		/**
		 * S​i​m​p​l​e​ ​i​n​v​o​i​c​e​ ​g​e​n​e​r​a​t​o​r​,​c​l​e​a​n​ ​i​n​v​o​i​c​e​ ​m​a​n​a​g​e​m​e​n​t​,​o​p​e​n​-​s​o​u​r​c​e​ ​i​n​v​o​i​c​i​n​g​ ​t​o​o​l​,​o​n​e​-​c​l​i​c​k​ ​i​n​v​o​i​c​i​n​g​,​f​r​e​e​l​a​n​c​e​r​ ​p​a​y​m​e​n​t​ ​m​a​n​a​g​e​m​e​n​t​,​r​e​m​o​t​e​ ​j​o​b​ ​p​a​y​m​e​n​t​ ​m​a​n​a​g​e​m​e​n​t​,​s​e​c​u​r​e​ ​i​n​v​o​i​c​e​ ​g​e​n​e​r​a​t​i​o​n​,​s​a​f​e​ ​p​a​y​m​e​n​t​ ​m​a​n​a​g​e​m​e​n​t​,​b​r​o​w​s​e​r​-​b​a​s​e​d​ ​i​n​v​o​i​c​i​n​g​,​c​l​i​e​n​t​-​s​i​d​e​ ​i​n​v​o​i​c​e​ ​d​a​t​a​ ​s​t​o​r​a​g​e​.
		 */
		keywords: string
		generator: {
			/**
			 * G​e​n​e​r​a​t​e​ ​I​n​v​o​i​c​e
			 */
			title: string
			meta: {
				/**
				 * G​e​n​e​r​a​t​e​ ​&​ ​p​r​i​n​t​ ​i​n​v​o​i​c​e​s​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​t​h​e​ ​s​p​e​c​i​f​i​e​d​ ​w​o​r​k​ ​l​o​g​ ​&​ ​u​n​i​t​.
				 */
				description: string
			}
		}
		preview: {
			/**
			 * P​r​e​v​i​e​w​ ​I​n​v​o​i​c​e
			 */
			title: string
			meta: {
				/**
				 * P​r​e​v​i​e​w​ ​y​o​u​r​ ​c​u​s​t​o​m​i​z​e​d​ ​i​n​v​o​i​c​e​ ​w​i​t​h​ ​e​a​s​e​ ​a​n​d​ ​e​n​s​u​r​e​ ​i​t​'​s​ ​p​e​r​f​e​c​t​ ​b​e​f​o​r​e​ ​s​e​n​d​i​n​g​ ​t​o​ ​c​l​i​e​n​t​s​.
				 */
				description: string
			}
		}
		pwa: {
			/**
			 * N​e​w​ ​c​o​n​t​e​n​t​ ​a​v​a​i​l​a​b​l​e​,​ ​c​l​i​c​k​ ​o​n​ ​r​e​l​o​a​d​ ​b​u​t​t​o​n​ ​t​o​ ​u​p​d​a​t​e​.
			 */
			newContentAvailable: string
			/**
			 * A​p​p​ ​r​e​a​d​y​ ​t​o​ ​w​o​r​k​ ​o​f​f​l​i​n​e
			 */
			workOffline: string
		}
	}
	invoicesTable: {
		head: {
			/**
			 * D​e​s​c​r​i​p​t​i​o​n
			 */
			description: string
			/**
			 * Q​t​y​ ​(​{​q​u​a​n​t​i​t​y​}​)
			 * @param {string} quantity
			 */
			qty: RequiredParams<'quantity'>
			/**
			 * R​a​t​e​ ​(​/​{​u​n​i​t​}​)
			 * @param {string} unit
			 */
			unitPrice: RequiredParams<'unit'>
			/**
			 * T​o​t​a​l​ ​P​r​i​c​e
			 */
			totalPrice: string
		}
		body: {
			/**
			 * S​u​b​t​o​t​a​l
			 */
			subtotal: string
			/**
			 * A​d​j​u​s​t​m​e​n​t​s
			 */
			adjustments: string
			/**
			 * T​o​t​a​l
			 */
			total: string
			/**
			 * {​q​u​a​n​t​i​t​y​}​ ​h​o​u​r​s​ ​a​t​ ​$​{​u​n​i​t​P​r​i​c​e​}
			 * @param {string} quantity
			 * @param {string} unitPrice
			 */
			quantityAtPrice: RequiredParams<'quantity' | 'unitPrice'>
		}
	}
	invoiceForm: {
		/**
		 * Y​o​u​r​ ​n​a​m​e
		 */
		yourName: string
		/**
		 * S​K​-​2​0​2​3​0​1​4
		 */
		invoiceNumber: string
		yourCompany: {
			/**
			 * Y​o​u​r​ ​c​o​m​p​a​n​y​ ​i​n​f​o​r​m​a​t​i​o​n
			 */
			info: string
			/**
			 * Y​o​u​r​ ​c​o​m​p​a​n​y​ ​n​a​m​e
			 */
			name: string
			/**
			 * C​i​t​y
			 */
			city: string
			/**
			 * P​o​s​t​a​l​ ​C​o​d​e
			 */
			postalCode: string
			/**
			 * C​o​u​n​t​r​y
			 */
			country: string
			srOnly: {
				/**
				 * Y​o​u​r​ ​c​o​m​p​a​n​y​ ​c​i​t​y
				 */
				city: string
				/**
				 * Y​o​u​r​ ​c​o​m​p​a​n​y​ ​P​o​s​t​a​l​ ​C​o​d​e
				 */
				postalCode: string
				/**
				 * Y​o​u​r​ ​c​o​u​n​t​r​y​ ​o​f​ ​o​r​i​g​i​n
				 */
				country: string
			}
		}
		toAddress: {
			/**
			 * W​h​e​r​e​ ​w​o​u​l​d​ ​y​o​u​ ​s​e​n​d​ ​t​h​i​s​ ​i​n​v​o​i​c​e​?
			 */
			title: string
			/**
			 * N​a​m​e​/​C​o​m​p​a​n​y
			 */
			name: string
			/**
			 * A​d​d​r​e​s​s
			 */
			address: string
			/**
			 * P​o​s​t​a​l​ ​C​o​d​e
			 */
			postalCode: string
			/**
			 * C​o​u​n​t​r​y
			 */
			country: string
		}
		fromAddress: {
			/**
			 * W​h​e​r​e​ ​i​s​ ​t​h​e​ ​i​n​v​o​i​c​e​ ​o​r​i​g​i​n​a​t​e​d​ ​f​r​o​m​?
			 */
			title: string
			/**
			 * N​a​m​e​/​C​o​m​p​a​n​y
			 */
			name: string
			/**
			 * A​d​d​r​e​s​s
			 */
			address: string
			/**
			 * P​o​s​t​a​l​ ​C​o​d​e
			 */
			postalCode: string
			/**
			 * C​o​u​n​t​r​y
			 */
			country: string
		}
		serviceItem: {
			/**
			 * L​a​n​d​i​n​g​ ​p​a​g​e​ ​d​e​s​i​g​n
			 */
			description: string
			/**
			 * 4​0​.​0
			 */
			quantity: string
			/**
			 * 5​5​.​0​0
			 */
			unitPrice: string
			/**
			 * 0​.​0​0
			 */
			adjustments: string
			/**
			 * S​p​e​c​i​a​l​i​z​e​d​ ​s​o​f​t​w​a​r​e​ ​i​s​ ​u​s​e​d​ ​t​o​ ​r​e​c​o​r​d​ ​t​h​e​ ​w​o​r​k​ ​h​o​u​r​s​ ​&​ ​c​a​n​ ​b​e​ ​s​e​n​t​ ​i​f​ ​n​e​c​e​s​s​a​r​y​.​ ​W​i​t​h​ ​t​h​i​s​,​ ​I​ ​c​o​n​f​i​r​m​ ​t​h​a​t​ ​a​l​l​ ​t​h​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​m​e​n​t​i​o​n​e​d​ ​a​b​o​v​e​ ​i​s​ ​c​o​r​r​e​c​t​ ​&​ ​v​a​l​i​d​a​t​e​d​.
			 */
			note: string
		}
		srOnly: {
			/**
			 * I​n​v​o​i​c​e​ ​N​u​m​b​e​r
			 */
			invoiceNumber: string
		}
	}
	/**
	 * Y​o​u​ ​c​a​n​ ​c​h​a​n​g​e​ ​t​h​e​ ​m​a​r​g​i​n​,​ ​s​c​a​l​e​/​z​o​o​m​,​ ​p​a​p​e​r​ ​s​i​z​e​,​ ​h​e​a​d​e​r​s​ ​&​ ​f​o​o​t​e​r​s​,​ ​e​t​c​.​,​ ​o​n​ ​t​h​e​ ​p​r​i​n​t​ ​d​i​a​l​o​g​.​ ​S​o​ ​f​e​e​l​ ​f​r​e​e​ ​t​o​ ​c​u​s​t​o​m​i​z​e​ ​i​t​ ​a​c​c​o​r​d​i​n​g​ ​t​o​ ​y​o​u​r​ ​n​e​e​d​s​.
	 */
	printCustomizationNote: string
}

export type TranslationFunctions = {
	common: {
		/**
		 * Generate
		 */
		generate: () => LocalizedString
		/**
		 * Preview
		 */
		preview: () => LocalizedString
		/**
		 * Change Theme
		 */
		changeTheme: () => LocalizedString
		/**
		 * Upload Logo
		 */
		uploadLogo: () => LocalizedString
		/**
		 * Company logo
		 */
		companyLogo: () => LocalizedString
		/**
		 * Invoice
		 */
		invoice: () => LocalizedString
		/**
		 * Submitted on {{string}}
		 */
		submittedOn: (arg: { date: number | string | boolean }) => LocalizedString
		/**
		 * Invoice for
		 */
		invoiceFor: () => LocalizedString
		/**
		 * Invoice from
		 */
		invoiceFrom: () => LocalizedString
		/**
		 * Due date
		 */
		dueDate: () => LocalizedString
		/**
		 * Note
		 */
		note: () => LocalizedString
		/**
		 * Work completed for
		 */
		workForDate: () => LocalizedString
		/**
		 * Date from
		 */
		dateFrom: () => LocalizedString
		/**
		 * Date to
		 */
		dateTo: () => LocalizedString
		/**
		 * Print
		 */
		print: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * hours
		 */
		hours: () => LocalizedString
		/**
		 * hr
		 */
		perHour: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Ok
		 */
		ok: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Reload
		 */
		reload: () => LocalizedString
		/**
		 * Are you sure?
		 */
		areYouSure: () => LocalizedString
		/**
		 * Currency
		 */
		currency: () => LocalizedString
		srOnly: {
			/**
			 * Currency symbol
			 */
			currencySymbol: () => LocalizedString
		}
	}
	pageSpecifics: {
		/**
		 * Simple One-click Invoice Generator for Freelancers and Remote Workers
		 */
		title: () => LocalizedString
		/**
		 * This is a very simple, clean, awesome-looking, open-source, one-click invoice generator application for freelancers & remote job holders to manage payments. All the data are saved on the client's browser. Nothing is saved anywhere so it is secure & safe.
		 */
		description: () => LocalizedString
		/**
		 * Simple invoice generator,clean invoice management,open-source invoicing tool,one-click invoicing,freelancer payment management,remote job payment management,secure invoice generation,safe payment management,browser-based invoicing,client-side invoice data storage.
		 */
		keywords: () => LocalizedString
		generator: {
			/**
			 * Generate Invoice
			 */
			title: () => LocalizedString
			meta: {
				/**
				 * Generate & print invoices according to the specified work log & unit.
				 */
				description: () => LocalizedString
			}
		}
		preview: {
			/**
			 * Preview Invoice
			 */
			title: () => LocalizedString
			meta: {
				/**
				 * Preview your customized invoice with ease and ensure it's perfect before sending to clients.
				 */
				description: () => LocalizedString
			}
		}
		pwa: {
			/**
			 * New content available, click on reload button to update.
			 */
			newContentAvailable: () => LocalizedString
			/**
			 * App ready to work offline
			 */
			workOffline: () => LocalizedString
		}
	}
	invoicesTable: {
		head: {
			/**
			 * Description
			 */
			description: () => LocalizedString
			/**
			 * Qty ({quantity})
			 */
			qty: (arg: { quantity: string }) => LocalizedString
			/**
			 * Rate (/{unit})
			 */
			unitPrice: (arg: { unit: string }) => LocalizedString
			/**
			 * Total Price
			 */
			totalPrice: () => LocalizedString
		}
		body: {
			/**
			 * Subtotal
			 */
			subtotal: () => LocalizedString
			/**
			 * Adjustments
			 */
			adjustments: () => LocalizedString
			/**
			 * Total
			 */
			total: () => LocalizedString
			/**
			 * {quantity} hours at ${unitPrice}
			 */
			quantityAtPrice: (arg: { quantity: string, unitPrice: string }) => LocalizedString
		}
	}
	invoiceForm: {
		/**
		 * Your name
		 */
		yourName: () => LocalizedString
		/**
		 * SK-2023014
		 */
		invoiceNumber: () => LocalizedString
		yourCompany: {
			/**
			 * Your company information
			 */
			info: () => LocalizedString
			/**
			 * Your company name
			 */
			name: () => LocalizedString
			/**
			 * City
			 */
			city: () => LocalizedString
			/**
			 * Postal Code
			 */
			postalCode: () => LocalizedString
			/**
			 * Country
			 */
			country: () => LocalizedString
			srOnly: {
				/**
				 * Your company city
				 */
				city: () => LocalizedString
				/**
				 * Your company Postal Code
				 */
				postalCode: () => LocalizedString
				/**
				 * Your country of origin
				 */
				country: () => LocalizedString
			}
		}
		toAddress: {
			/**
			 * Where would you send this invoice?
			 */
			title: () => LocalizedString
			/**
			 * Name/Company
			 */
			name: () => LocalizedString
			/**
			 * Address
			 */
			address: () => LocalizedString
			/**
			 * Postal Code
			 */
			postalCode: () => LocalizedString
			/**
			 * Country
			 */
			country: () => LocalizedString
		}
		fromAddress: {
			/**
			 * Where is the invoice originated from?
			 */
			title: () => LocalizedString
			/**
			 * Name/Company
			 */
			name: () => LocalizedString
			/**
			 * Address
			 */
			address: () => LocalizedString
			/**
			 * Postal Code
			 */
			postalCode: () => LocalizedString
			/**
			 * Country
			 */
			country: () => LocalizedString
		}
		serviceItem: {
			/**
			 * Landing page design
			 */
			description: () => LocalizedString
			/**
			 * 40.0
			 */
			quantity: () => LocalizedString
			/**
			 * 55.00
			 */
			unitPrice: () => LocalizedString
			/**
			 * 0.00
			 */
			adjustments: () => LocalizedString
			/**
			 * Specialized software is used to record the work hours & can be sent if necessary. With this, I confirm that all the information mentioned above is correct & validated.
			 */
			note: () => LocalizedString
		}
		srOnly: {
			/**
			 * Invoice Number
			 */
			invoiceNumber: () => LocalizedString
		}
	}
	/**
	 * You can change the margin, scale/zoom, paper size, headers & footers, etc., on the print dialog. So feel free to customize it according to your needs.
	 */
	printCustomizationNote: () => LocalizedString
}

export type Formatters = {}
